name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  autosquash:
    name: Autosquash
    runs-on: ubuntu-18.04
    steps:
      - uses: tibdex/autosquash@v2
        with:
          # We can't use the built-in secrets.GITHUB_TOKEN yet because of this limitation:
          # https://github.community/t5/GitHub-Actions/Triggering-a-new-workflow-from-another-workflow/td-p/31676
          # In the meantime, use a token granting write access on the repo:
          # - a GitHub App token
          #   See https://github.com/marketplace/actions/github-app-token.
          # - a personal access token
          #   See https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line.
          github_token: ${{ secrets.AUTOSQUASH_TOKEN }}
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Testing
        run: |
          xcodebuild clean build -project CustomDropDown.xcodeproj -scheme CustomDropDown -sdk iphonesimulator -destination"platform=iOS Simulator,OS=13.1,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
